# Generated by Django 5.0 on 2023-12-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='book_covers/Empty.png', null=True, upload_to='book_covers/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
    ]
