# Generated by Django 5.0 on 2024-01-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='book_covers/Empty.png', upload_to='book_covers/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
    ]
